version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/awm  " # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/awm-jasonernst  " # Location of package manifests
    schedule:
      interval: "daily"
