# https://reflectoring.io/fully-automated-open-source-release-chain/

sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools

    - extra-google-google_play_services
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

stages:
  - name: build
  - name: snapshot
    if: branch = master
  - name: release
    if: branch = release

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: snapshot
      script: ./gradlew build
    - stage: release
      script: ./gradlew bintrayUpload -Dbintray.user=$bintray.user -Dbintray.key=$bintray.key -Dgpgpassphrass=$gpgpassphrase -Dbuild.number=$TRAVIS_BUILD_NUMBER

before_install:
  - pwd
  - ls -la
  - chmod +x /.gradlew
