version: '2.3'
services:
  php-apache:
    container_name: php-apache-awm-server-php
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ../awm-server-php:/var/www/html/
    ports:
      - 8000:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MAPSKEY: ${MAPSKEY}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  db:
    container_name: db-awm-server-php
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ../awm-server-php/wireless_stats.sql:/docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
