version: '2'
services:
  mysql:
    image: mysql:8.0
    container_name: awm-sql
    restart: always
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - awm-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    links:
      - mysql:db
    ports:
      - 8080:80
    networks:
      - awm-net

  nginx:
    image: nginx:1.24.0-alpine
    container_name: awm-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - awm-net

  app:
    container_name: awm-app
    build:
      args:
        user: jason
        uid: 1000
      context: .
      target: app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: "/var/www/html/entrypoint.sh"
    depends_on:
      - mysql
      - nginx
    env_file: .env
    networks:
      - awm-net

networks:
  awm-net:
    driver: bridge